services:
  web:
    image: simon7426/vue-portfolio:0.3
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/simon-portfolio/Certs/simonislam.com.crt:/usr/share/nginx/simonislam.com.crt
      - /home/ubuntu/simon-portfolio/Certs/simonislam.com.key:/usr/share/nginx/simonislam.com.key
    depends_on:
      - leetcode-api
  leetcode-api:
    image: simon7426/vue-portfolio-leetcode:0.2
    restart: always
    ports:
      - 8000:8000